[workspace]
members = [
  "profile",
  "accelsim",
  "trace",
  "trace/invoke"
]

[profile.dev]
opt-level = 0
debug = 1

[profile.release]
lto = true

[package]
name = "casimu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive"] }
profile = { path = "./profile" }
accelsim = { path = "./accelsim" }
invoke_trace = { path = "./trace/invoke" }
serde_json = "1"
