[workspace]
members = [
  "validate",
  "profile",
  "accelsim",
  "plot",
  "trace",
  "trace/invoke",
  "trace/model"
]

[profile.dev]
opt-level = 0
debug = 1

[profile.release]
lto = true

[package]
name = "casimu"
version = "0.1.0"
edition = "2021"

[features]
default = ["python"]
python = ["dep:pyo3"]

[package.metadata.cargo-feature-combinations]
denylist = ["default"]

[dependencies]
anyhow = "1"
thiserror = "1"
nvbit-model = "0"
nvbit-io = "0"
num-traits = "0"
itertools = "0"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1"

pyo3 = { version = "0", features = ["extension-module"], optional = true }

trace-model = { path = "./trace/model" }

[dev-dependencies]
