[workspace]
members = [
  "profile",
  "accelsim"
]

[profile.dev]
opt-level = 0
debug = 1

[profile.release]
lto = true

[package]
name = "casimu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
