[workspace]
members = [
  "validate",
  "profile",
  "accelsim",
  "trace",
  "trace/invoke",
  "trace/model"
]

[profile.dev]
opt-level = 0
debug = 1

[profile.release]
lto = true

[package]
name = "casimu"
version = "0.1.0"
edition = "2021"

[features]
default = []

[package.metadata.cargo-feature-combinations]
denylist = ["default"]

[dependencies]
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive"] }
trace-model = { path = "./trace/model" }
nvbit-model = "0"
nvbit-io = "0"
nvbit-rs = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1"
num-traits = "0"
itertools = "0"

# default = ["remote"]
# remote = ["dep:ssh_jumper"]
# profile = { path = "./profile" }
# accelsim = { path = "./accelsim" }
# dotenv = "0"
# tokio = { version = "1", features = ["full"] }
# ssh_jumper = { version = "0", optional = true }
# trace = { path = "./trace" }
# tokio = { version = "1", features = ["full"], optional = true }
