[workspace]
members = [
  "validate",
  "profile",
  "playground",
  "accelsim",
  "utils",
  "plot",
  "trace",
  "trace/invoke",
  "trace/model",
  "xtask",
]

[profile.dev]
opt-level = 0 # no optimizations
debug = 2 # full debug info

[profile.release]
lto = true

[package]
name = "casimu"
version = "0.1.0"
edition = "2021"

[features]
default = []
# default = ["python"]
python = ["dep:pyo3"]

[package.metadata.cargo-feature-combinations]
denylist = ["default"]

[dependencies]
trace-model = { path = "./trace/model" }
color-eyre = "0"
human_bytes = "0"
console = "0"
thiserror = "1"
nvbit-model = "0"
nvbit-io = "0"
regex = "1"
itertools = "0"
csv = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1"
log = "0"
bitvec = "1"
strum = { version = "0", features = ["derive"] }
phf = { version = "0.11.1", features = ["macros"] }
dialoguer = "0"
# for vectoradd rust example
num-traits = "0"

[dependencies.pyo3]
version = "0"
features = ["extension-module"]
optional = true

[dev-dependencies]
playground = { path = "./playground" }
pretty_assertions = "1"
cxx = "1"
