[package]
name = "remote"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0"
ssh_jumper = "0"
color-eyre = "0"
thiserror = "1"

tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
