[package]
name = "profile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
thiserror = "1"
tempfile = "3"
csv = "1"
serde = "1"
serde_json = "1"
lazy_static = "1"
regex = "1"
clap = { version = "4", features = ["derive"] }
