[package]
name = "accelsim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default  = []

[package.metadata.cargo-feature-combinations]
denylist = ["default"]

[dependencies]
thiserror = "1"

[build-dependencies]
glob = "0"
