[package]
name = "validate"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["remote"]
remote = ["dep:ssh_jumper"]

[package.metadata.cargo-feature-combinations]
denylist = ["default"]

[package.metadata.cargo-feature-combinations.matrix]
need_cuda = true

[dependencies]
thiserror = "1"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
dotenv = "0"
invoke-trace = { path = "../trace/invoke" }
profile = { path = "../profile" }
accelsim = { path = "../accelsim" }
trace-model = { path = "../trace/model" }
serde_json = "1"

ssh_jumper = { version = "0", optional = true }
