[package]
name = "playground"
version = "0.1.0"
edition = "2021"
build = "build.rs"
exclude = [
  # debug bindings file
  "./bindings.rs"
]

[lib]
# crate-type = ["staticlib"]
# crate-type = ["cdylib"]
crate-type = ["rlib"]

[features]
default = []
parallel = ["cc/parallel"]

[dependencies]
cxx = "1"

[dev-dependencies]
pretty_assertions = "1"

[build-dependencies]
bindgen = "0"
cc = { version = "1", features = [] }
cxx-build = "1"
