[package]
name = "trace-model"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
nvbit-model = "0"
itertools = "0"

[dev-dependencies]
similar-asserts = "1"
