name: build
on: [push, pull_request]
jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yml
  build:
    name: build ${{ matrix.package.name }} (${{ matrix.package.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install accelsim dependencies
        if: ${{ matrix.package.name == 'accelsim-sim' }}
        run: >-
          sudo apt-get install -y wget build-essential xutils-dev bison zlib1g-dev flex libglu1-mesa-dev libssl-dev libxml2-dev libboost-all-dev git g++
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.10
        id: cuda-toolkit
        if: ${{ matrix.package.need_cuda }}
        with:
          cuda: "11.8.0"
          use-github-cache: false
          linux-local-args: '["--driver", "--toolkit"]'
      - name: Build all
        run: >-
          cargo build  --package "${{ matrix.package.name }}" --features "${{ matrix.package.features }}" --all-targets
